### ISSUE TITLE
error specific to python2.7: AttributeError: 'module' object has no attribute 'instancemethod'

### ISSUE THREAD

**Issue by sagaru** [wolever/parameterized#35]
Hello,

I'm getting "AttributeError: 'module' object has no attribute 'instancemethod'" whenever I use nose-parameterized in python 2.7, the s same script(mentioned below) **executes fine in python3.4**.

Anyone has an idea or faced similar issue ?

**Code** : 

```
import unittest
from nose_parameterized import parameterized

class autologinTest(unittest.TestCase):
    a = [(['domain', 'url_login', 'logoutXpath']) , (['domain2', 'url_login2', 'logoutXpath2'])]
    print(a)

    @parameterized.expand(a)
    def test_generic_function(self, a, b, c):
        print a,b,c
```

**Error Traceback in python2.7** :

```
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/helpers/pycharm/utrunner.py", line 153, in <module>
    modules = [loadSource(a[0])]
  File "/Applications/PyCharm.app/Contents/helpers/pycharm/utrunner.py", line 65, in loadSource
    module = imp.load_source(moduleName, fileName)
  File "/Users/sudaykumar/Documents/Automation/autologin_POC/testing.py", line 4, in <module>
    from nose_parameterized import parameterized
  File "/Library/Python/2.7/site-packages/nose_parameterized/__init__.py", line 1, in <module>
    from .parameterized import parameterized, param
  File "/Library/Python/2.7/site-packages/nose_parameterized/parameterized.py", line 31, in <module>
    new_instancemethod = new.instancemethod
AttributeError: 'module' object has no attribute 'instancemethod'
```

**Comment by wolever** [comment]
Hey,

Sorry for the delayed reply here! I suspect the issue is that you've got another module named`new` on your path. To find out, run `python -c 'import new; print new.__file__'`. It should be `…/lib/python2.7/new.pyc`. If so, let me know! If not, then you'll have to figure out where the errant `new` module is coming from.
