### ISSUE TITLE
Tests throw a unicode error with Python 2.7

### ISSUE THREAD

**Issue by ghisvail** [wolever/parameterized#44]
I have packaged `parameterized` for Debian, since it is a required dependency for testing other packages. Its test suite runs fine at package build time, but it fails against the installed package for Python 2. The tests run fine for Python 3. Here is the relevant portion of the Debian CI [log](https://ci.debian.net/data/autopkgtest/unstable/amd64/p/python-parameterized/20170830_143838/log.gz):

```
test command1: set -e ; for py in $(pyversions -r 2>/dev/null) ; do cd "$AUTOPKGTEST_TMP" ; echo "Testing with $py (unittest):" ; $py -m unittest -v parameterized.test ; echo "Testing with $py (nose):" ; $py -m nose -v parameterized.test ; echo "Testing with $py (nose2):" ; $py -m nose2 -v parameterized.test ; echo "Testing with $py (pytest):" ; $py -m pytest -v --pyargs parameterized.test ; done
autopkgtest [14:39:04]: test command1: [-----------------------
Testing with python2.7 (unittest):
test_on_TestCase2_custom_name_42 (parameterized.test.TestParamerizedOnTestCase) ... ok
test_on_TestCase2_custom_name_foo0 (parameterized.test.TestParamerizedOnTestCase) ... ok
test_on_TestCase2_custom_name_foo1 (parameterized.test.TestParamerizedOnTestCase) ... ok
test_on_TestCase2_custom_name_foo2 (parameterized.test.TestParamerizedOnTestCase) ... ok
test_on_TestCase_0 (parameterized.test.TestParamerizedOnTestCase) ... ok
test_on_TestCase_1_foo0 (parameterized.test.TestParamerizedOnTestCase) ... ok
test_on_TestCase_2_foo1 (parameterized.test.TestParamerizedOnTestCase) ... ok
test_on_TestCase_3_foo2 (parameterized.test.TestParamerizedOnTestCase) ... ok
test_custom_doc_func_0_foo (parameterized.test.TestParameterizedExpandDocstring)
stuff ... ok
test_default_values_get_correct_value_0_foo (parameterized.test.TestParameterizedExpandDocstring)
Documentation [with foo='foo', bar=12] ... ok
test_empty_docstring_0_foo (parameterized.test.TestParameterizedExpandDocstring)
[with foo='foo'] ... ok
test_multiline_documentation_0_foo (parameterized.test.TestParameterizedExpandDocstring)
Documentation [with foo='foo']. ... ok
test_single_line_docstring_0_foo (parameterized.test.TestParameterizedExpandDocstring)
Documentation [with foo='foo']. ... ok
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/unittest/__main__.py", line 12, in <module>
    main(module=None)
  File "/usr/lib/python2.7/unittest/main.py", line 95, in __init__
    self.runTests()
  File "/usr/lib/python2.7/unittest/main.py", line 232, in runTests
    self.result = testRunner.run(self.test)
  File "/usr/lib/python2.7/unittest/runner.py", line 151, in run
    test(result)
  File "/usr/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/usr/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/usr/lib/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/suite.py", line 108, in run
    test(result)
  File "/usr/lib/python2.7/unittest/case.py", line 393, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib/python2.7/unittest/case.py", line 304, in run
    result.startTest(self)
  File "/usr/lib/python2.7/unittest/runner.py", line 53, in startTest
    self.stream.write(self.getDescription(test))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 84: ordinal not in range(128)
```

**Comment by wolever** [comment]
Hey! Is this still an issue? Please feel free to re-open if so 🙂
