### ISSUE TITLE
Supplying tuple/list as single test argument?

### ISSUE THREAD

**Issue by Poddster** [wolever/parameterized#56]
This doesn't work:

    @parameterized([
        [1, 1, 1, 1, 1],
        [1, 2, 2],
        [2, 3,],
        [5],
    ])
    def test_list(self, data):
        assert sum(data) == 5

As it results in these errors:

    ======================================================================
    ERROR: <snip>.test_list(2, 3)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "c:\dev\env\python\python27\lib\site-packages\nose\case.py", line 197, in runTest
        self.test(*self.arg)
      File "c:\dev\env\python\python27\lib\site-packages\parameterized\parameterized.py", line 280, in <lambda>
        nose_func = wraps(func)(lambda *args: func(*args))
    TypeError: test_list() takes exactly 2 arguments (3 given)
    
    ======================================================================
    ERROR: <snip>.test_list(5,)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "c:\dev\env\python\python27\lib\site-packages\nose\case.py", line 197, in runTest
        self.test(*self.arg)
      File "c:\dev\env\python\python27\lib\site-packages\parameterized\parameterized.py", line 280, in <lambda>
        nose_func = wraps(func)(lambda *args: func(*args))
      File "C:\dev\work\MPI-Test\pyMPI-Test\pem\tests\test_pem_robot.py", line 574, in test_list
        assert sum(data) == 5
    TypeError: 'int' object is not iterable

The lists have to be wrapped in useless lists for it to work:

    @parameterized([
        [[1, 1, 1, 1, 1]],
        [[1, 2, 2]],
        [[2, 3,]],
        [[5]],
    ])
    def test_list(self, data):
        assert sum(data) == 5

What is the "official" way of supplying iterables as test data with `@parameterized`? Would it be possible to note the proper idiom in the "Exhaustive Usage Examples"?

**Comment by wolever** [comment]
Good idea, thanks! I've updated the README to include an example.
