### ISSUE TITLE
Support marks?

### ISSUE THREAD

**Issue by EWouters** [wolever/parameterized#70]
Hi, is it possible to set marks to a parameterized test? Something like this:
```
@parameterized.expand([
        (CHANNEL_A, POWER_CURRENT),
        pytest.param(CHANNEL_B, POWER_CURRENT, marks=pytest.mark.xfail),
        pytest.param(CHANNEL_A, POWER_VOLTAGE, marks=pytest.mark.xfail),
        pytest.param(CHANNEL_B, POWER_VOLTAGE, marks=pytest.mark.xfail),
        pytest.param(CHANNEL_A, POWER_RANGE, marks=pytest.mark.xfail),
        pytest.param(CHANNEL_B, POWER_RANGE, marks=pytest.mark.xfail)])
```

**Comment by videetparekh** [comment]
Facing the same issue. 
Attempting to dynamically create tests using a config file. 
```
def load_config_file(path):
    with open(path) as f:
        configs = json.load(f)
    params=[]
    for config in configs:
        if not config.get('skip', False):
            if config.get('xfail', False):
                param = pytest.param(config, marks=pytest.mark.xfail)
            else: 
                param = (config,)
            params.append(param)
    return params

...

class UnitTestCase(unittest.TestCase):
    @parameterized.expand("config", load_config_file('tests/config.json'))
    def test_main(self, config):         
        print("Do some stuff with config {}".format(config))
```

I get the error:
```
Traceback (most recent call last):
  File "xxxxxxxxxxx", line 30, in <module>
    class UnitTestCase(unittest.TestCase):
  File "xxxxxxxxxx", line 48, in AudioRecognitionCompressUnitTestCase
    @parameterized.expand("config", load_config_file('tests/config.json'))
  File "/usr/local/lib/python3.6/dist-packages/parameterized/parameterized.py", line 498, in parameterized_expand_wrapper
    name = name_func(f, "{num:0>{digits}}".format(digits=digits, num=num), p)
TypeError: 'list' object is not callable
```

Is there any way for me to mark a test case xfail using the config values and passing it to a parameterized function?
